# Generated by Django 5.2.17 on 2026-09-06 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='nacionalidad')),
                ('anio_nacimiento', models.PositiveIntegerField(verbose_name='año de nacimiento')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('anio_publicacion', models.PositiveIntegerField(verbose_name='año de publicación')),
                ('paginas', models.PositiveIntegerField(verbose_name='páginas')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=10, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='catalogo.autor', verbose_name='autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['titulo'],
                'constraints': [models.UniqueConstraint(fields=('titulo', 'autor'), name='libro_unico_por_autor')],
            },
        ),
    ]
